version: '3.3'

services:
  mongo:
    image: mongo:3.7.3-jessie
    volumes:
      - datavolume:/data/db
    restart: unless-stopped
  node:
    image: upe-coding-challenge/node:latest
    build: node
    volumes:
      - ./node/:/app
    depends_on:
      - mongo
    restart: unless-stopped

  nginx:
    image: upe-coding-challenge/nginx:latest
    build: nginx
    ports:
      - "42069:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    restart: unless-stopped

volumes:
  datavolume:
